server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: true
      server:
        native:
          searchLocations: 'classpath:/configuration/'
  profiles:
    active: native